from .user import User
from .farmer import Farmer
from .farm import Farm
from .disease import Disease
from .treatment import Treatment
from .disease_prediction import DiseasePrediction
from .soil_record import SoilRecord
from .weather_record import WeatherRecord
from .crop_recommendation import CropRecommendation
from .notification import Notification
